---
title: "NBA Scoring (2008)"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
library(knitr)
library(d3heatmap)
library(flexdashboard)
library(readxl)
library(readr)
library(data.table)
library(dplyr)
library(dtplyr)
library(ggplot2)
library(lubridate)
library(plotly)

library(readxl)

Activite_Web_Quotidien <- read_excel("C:/Users/Julien/Desktop/TPG/Activité Web Quotidien (1).xlsx", skip = 3)

Activite_Web_Quotidien$DATECOMMANDE <- 
  as.POSIXct(Activite_Web_Quotidien$DATECOMMANDE * (60*60*24)
             , origin="1899-12-30"
             , tz="GMT")

Activite_Web_Quotidien$DATECOMMANDE <- as.Date(Activite_Web_Quotidien$DATECOMMANDE)
row.names(Activite_Web_Quotidien) <- as.character(Activite_Web_Quotidien$DATECOMMANDE)
ActWQuotNoDate <- Activite_Web_Quotidien[,2:27]
ActWQuotNoDate

row.names(ActWQuotNoDate) <- as.character(Activite_Web_Quotidien$DATECOMMANDE)
```

Row
-----------------------------------------------------------------------

### Articles per Day

```{r}
articles <- 1230000
valueBox(articles, icon = "fa-pencil")
```

### Comments per Day

```{r}
comments <- 154
valueBox(comments, icon = "fa-comments")
```

### Spam per Day

```{r}
spam <- 143
valueBox(spam, 
         icon = "fa-trash",
         color = ifelse(spam > 10, "warning", "primary"))
```

Row
-----------------------------------------------------------------------

### Stats by Player {data-width=650}


```{r}
d3heatmap(ActWQuotNoDate, scale = "column")
```

### Top Scorers {data-width=350}

```{r}
knitr::kable(Activite_Web_Quotidien[1:20,c("DATECOMMANDE", "CAHTWEB", "NBCMD")])
```

Row
-----------------------------------------------------------------------


### Nb commandes par jour {data-width=650}

```{r}
plot_ly(Activite_Web_Quotidien, x = ~DATECOMMANDE, y = ~NBCMD, name = 'Nb Cmd Total', type = 'scatter', mode = 'lines') %>%
  add_trace(y = ~NB3EANECMD, name = 'Nb 3e et + cmd', mode = 'lines') %>% 
  add_trace(y = ~NB2ECMD, name = 'Nb 2e cmd', mode = 'lines') %>%
   add_trace(y = ~NB1ERECMD, name = 'Nb 1ere cmd', mode = 'lines')
```